version: '2'
services:

  seleniumhub:
    restart: always
    container_name: seleniumhub
    image: sportyturks-selenium-hub:latest
    ports:
      - "4444:4444"

  selenium:
    restart: always
    container_name: selenium
    image: sportyturks-selenium-node-chrome:latest
    ports:
      - "5555:5555"
    shm_size: 128M
    depends_on:
      - seleniumhub
    environment:
      - HUB_PORT_4444_TCP_ADDR=seleniumhub
      - HUB_PORT_4444_TCP_PORT=4444
